### ISSUE TITLE
missing permission/login checks in webservices

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#10]
when defining custom webservices that can be called directly - you need to implement login and capability checks prior to passing them to internal functions eg:

https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/bookmarks/classes/external.php#L56
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/note/classes/external.php#L55

and possibly other locations too.

You need to check:
is user logged in.
is "this" user allowed to do this thing (capability checks)
Is this user allowed to save for this userid. (are they passing someone else's userid in the data array?) - I'm not even sure you should allow userid to be passed in the array - and I suspect you should just be using the global $USER object instead.

**Comment by stefanscholz** [comment]
We have implemented the login and capabilities checking functions on external functions. 
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/dev/ltool/bookmarks/classes/external.php#L56

**Comment by stefanscholz** [comment]
![webservice_conditions](https://user-images.githubusercontent.com/3414705/156058160-36612e03-d57c-4903-b5f0-e687de42dfbd.png)
