### ISSUE TITLE
The button makes using the built-in messaging impossible

### ISSUE THREAD

**Issue by roessling** [bdecentgmbh/moodle-local_learningtools#13]
When installed, the button is placed at the bottom right of the screen. There, it occludes the area where the messaging interface has its "insert emoji" and, more importantly, "submit" buttons. If the site has configured messages to be sent on pressing Return, that is not very problematic, but if it has not (in favour of longer, but fewer, messages), it makes sending a message difficult to impossible.

**Comment by stefanscholz** [comment]
Hi @roessling ,

thanks for reporting this. We'll fix this in the next minor release. Until then, you can use this css to hotfix it:

`.floating-button {
    z-index: 1005;
}`

Hope this helps!
Stefan

**Comment by stefanscholz** [comment]
Hotfix applied on dev branch and deployed to labs.bdecent.de — after some testing, we'll release it to moodle.org
@roessling  fyi

**Comment by roessling** [comment]
Thank you for the fast reaction!
