### ISSUE TITLE
Problems with choosing specific category and users

### ISSUE THREAD

**Issue by kenh-zealand** [bdecentgmbh/moodle-local_learningtools#16]
I receive an error message, when trying to access the Moodle User as admin. My provider says, when Learning Tools is set to be active on a specific category. This happens.

We hope you can help us out in this.

- Kenneth

![learning tools 1](https://user-images.githubusercontent.com/105286493/167618303-251282ed-048f-430e-887f-2dba61f31dc7.jpg)
![learning tools 2](https://user-images.githubusercontent.com/105286493/167618311-b9a0e982-7d02-4e81-93d9-7913828686c5.jpg)

**Comment by stefanscholz** [comment]
Hi @kenh-zealand ,

thanks for reporting this issue. We've just released a new version which fixes this bug.
You can find it here: https://moodle.org/plugins/local_learningtools/versions
(please make sure you pick the right version for your moodle version)

All the best
Stefan
