### ISSUE TITLE
install.xml looks hand-rolled

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#2]
The install.xml files look like they may have been hand-rolled so contain a few inconsistencies / spacing issues.

ideally this should be fixed using the Moodle xmldb editor (under admin > development > XMLDB.)

Please hit the "load" link for your plugin install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

not a blocker for approval though.

**Comment by stefanscholz** [comment]
We have updated all the install.XML files using Moodle XMLDB editor tool.
