### ISSUE TITLE
Feature request: Time Management overview of status of all students

### ISSUE THREAD

**Issue by jonathanpattison-sudo** [bdecentgmbh/moodle-local_learningtools#25]
It would be great if it was possible for a teacher to see an overview of all their students and an indication given as to whether they have fallen behind or not. This is essential functionality because none of the core reports (activity completion etc) include relative dates. Currently, Time Management only displays one student's progress.

![image](https://github.com/user-attachments/assets/cc1885c6-43bc-481d-a7a8-919f8c73b542)

**Comment by stefanscholz** [comment]
Hi @jonathanpattison-sudo ,

We recently implemented a Dash data source for Activity Completions which includes the dates. Feel free to schedule an online session and I can show it to you. It's currently available as preview for Dash Premium customers but will become part of Dash Pro in the next release.

Also note that we are working on a new release of Time Management, if you'd like to learn more about it, I'm happy to share the current concepts for it as well!

All the best
Stefan

**Comment by stefanscholz** [comment]
As explained above, this is covered by our Dash plugin. Won't implement in Time Management.
