### ISSUE TITLE
Feature Request: Time Management - Groups

### ISSUE THREAD

**Issue by jonathanpattison-sudo** [bdecentgmbh/moodle-local_learningtools#26]
Is there a way to get the Time Management plugin to recognise groups? It seems to be displaying activities from groups the learner is not a member of, which we don't want. Perhaps a feature request for a future revision?

**Comment by stefanscholz** [comment]
Hi @jonathanpattison-sudo, currently I'm afraid that's not possible. But I can add this to the roadmap, so that it gets implemented with the next major release. If you need this urgently, let me know and I can see what we can do.

**Comment by stefanscholz** [comment]
The next version of Time Management will support that, but not the current one. I've added it to the roadmap, thus closing it here.
