### ISSUE TITLE
uninstall/drop tables not needed

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#3]
Where a plugin uses the correct frankenstlye naming - when uninstalling a plugin all tables that are prefixed correctly with the frankenstyle plugin name will be uninstalled - this stuff shouldn't be needed:
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/db/uninstall.php#L31

... not a blocker for approval.

**Comment by stefanscholz** [comment]
We have converted the local plugin and all its sub plugins table names to correct moodle name standard.
