### ISSUE TITLE
custom actions should check sesskey

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#4]
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/learningtoolslist.php#L52
see:
https://docs.moodle.org/dev/Security:Cross-site_request_forgery#What_you_need_to_do_in_your_code

**Comment by stefanscholz** [comment]
We have implemented the moodle session key test for all the learning tools actions like create, delete of bookmarks, notes, and others.
