### ISSUE TITLE
functions in lib.php violates naming rules.

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#5]
functions must use the frankenstyle naming or sit within namespaced classes - see:
https://docs.moodle.org/dev/Frankenstyle#Function_names

for example - functions like get_module_id() could clash with a core function - it should be prefixed with the frankenstyle prefix eg:
local_learningtools_get_module_id()

Please check all functions and make sure they are either in namespaced classes or prefixed with the plugin frankenstyle name.

note - this is a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
other examples of violations of the naming conventions:
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/bookmarks/lib.php#L103
(you should check all lib.php files in your subplugins)

also - we have naming conventions for constants too - this could cause conflicts with core code:
```
define('BOOKMARK_SHORTNAME', 'bookmarks');
```
see the frankenstyle naming convention page above for info on contant naming.

**Comment by stefanscholz** [comment]
We have added the plugin type and plugin name (local_learningtools) with all the function names in lib files. Also, updated the function names in sub plugins too.
