### ISSUE TITLE
hard-coded "student" role access

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#7]
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/lib.php#L441

Please don't hard-code things to the "student" role - many orgnaisations will rename this role, or have mulitple roles that provide student style access within a course. - It would be better for your plugin to define a new capability given to the student role by defaul and then do a capability based check rather than a role based check..

Note - hard-coded role names is a blocker for approval.

**Comment by stefanscholz** [comment]
We have removed the direct student role uses and used the role archetype to get the student roles. We found most places in moodle core used this method to get student users from the course. 

https://github.com/bdecentgmbh/moodle-local_learningtools/blob/dev/lib.php#L442

**Comment by danmarsden** [comment]
no that's still incorrect... as mentioned you should really create a new capability in your plugin assigned to students by default and check that. - not all learners within a course will have that archetype set, and there may also be users inside a course with a archetype set to student that are not learners but supporting learners, and so to give organisations the flexibility to define who a student is, we use capabilities:
more info on this is here:
https://docs.moodle.org/dev/Access_API

**Comment by mudrd8mz** [comment]
I agree with Dan here. In 99.99% of cases, the right way is to define the capability (with the archetype defaults) in db/access.php
