### ISSUE TITLE
sorttype needs better validation/cleaning

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#8]
your sorttype param should definitely not be a PARAM_TEXT - possibly a PARAM_ALPHA 
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/bookmarks/list.php#L42

and then you should need to check/sanitise it before it's passed directly into in-line SQL queries eg here:
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/bookmarks/classes/bookmarkstool_filter.php#L166

I'd reccomend you review all your optional_params - especially those set to PARAM_TEXT and see if they should be PARAM_ALPHA or PARAM_ALPHANUM style options.

**Comment by stefanscholz** [comment]
We have removed the direct inclusion of sort methods into SQL queries and replaced them with custom values.
 https://github.com/bdecentgmbh/moodle-local_learningtools/blob/dev/ltool/bookmarks/list.php#L41, 
 https://github.com/bdecentgmbh/moodle-local_learningtools/blob/dev/ltool/bookmarks/classes/bookmarkstool_filter.php#L173
