### ISSUE TITLE
consider using a string to store date formats

### ISSUE THREAD

**Issue by danmarsden** [bdecentgmbh/moodle-local_learningtools#9]
https://github.com/bdecentgmbh/moodle-local_learningtools/blob/main/ltool/bookmarks/classes/bookmarkstool_filter.php#L250

many langauges display dates in different ways - for that reason moodle typically stores these values in lang files - you can use the core_langconfig file which has a bunch but you can also define your own ones in the plugin lang file as well.

here's a direct link to the core_lanconfig with examples:
https://github.com/moodle/moodle/blob/master/lang/en/langconfig.php

not a blocker for approval.

**Comment by stefanscholz** [comment]
We have updated the date methods to moodle language pack-based. now we used the language strings instead of standard time methods.

https://github.com/bdecentgmbh/moodle-local_learningtools/blob/dev/ltool/bookmarks/classes/bookmarkstool_filter.php#L256
